spring:
  datasource:
    url: jdbc:mysql://192.168.6.119:3306/pobo_mhall?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: pobo_mhall
    password: 12345678
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: false # logging 里面已经打印了，这里就不打印了
    hibernate:
      ddl-auto: validate # validate | update | create | create-drop
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect