spring:
  resources:
    chain:
      strategy:
        fixed:
          enabled: true
          paths: /static/
          version: 0.0.1
    add-mappings: false
  profiles:
    include:
      - dao
      - service
  mvc:
    throw-exception-if-no-handler-found: true
server:
  port: 8080

